const nextConfig = {
  i18n: {
    locales: [
      "en",
      "en-us",
      "de",
      "es",
      "fr",
      "ar",
      "ko",
      "it",
      "pt",
      "ru",
      "zh",
      "de-de",
      "en-au",
      "en-ca",
      "en-gb",
      "en-in",
      "en-jp",
      "en-kr",
      "en-nz",
      "en-pr",
      "en-pt",
      "en-sg",
      "es-ar",
      "es-cl",
      "es-co",
      "es-cr",
      "es-do",
      "es-ec",
      "es-es",
      "es-mx",
      "es-pe",
      "es-pr",
      "es-us",
      "es-ve",
      "fr-ca",
      "hi",
      "hi-in",
      "it-it",
      "ja-jp",
      "ko-kr",
      "pt-br",
      "pt-pt",
    ],
    defaultLocale: "en",
    domains: [
      {
        domain: "usw-p-sc-nextc.merckmanuals.com",
        defaultLocale: "en-us",
      },
      {
        domain: "usw-p-sc-nextc.msdmanuals.com",
        defaultLocale: "en",
      },
    ],
  },
  // Add any other Next.js configuration options here
};

module.exports = nextConfig;
